spring:
  application:
    name: employee-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password: altir
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.user.server-url}/realms/${keycloak.user.realm}

    # Keycloak
keycloak:
  user:
     server-url: http://localhost:8180
     realm: employee-management
  admin:
        server-url: http://localhost:8180
        realm: employee-management
        client-id: employee-management-service
        client-secret: Dlh1NajE90pEBIwpI0nuhY9ZsOvlnGgq
fn:
  data:
    access:
      mapping:
        createToOneReferencesIfRequired: true


